[build]
  command = "cross-env NODE_ENV=prod gulp"
  functions = "functions"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-pr-bot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  "/*" = [
    "Cache-Control: public, max-age=0, must-revalidate",
    "X-Frame-Options: DENY",
    "X-XSS-Protection: 1; mode=block",
    "X-Content-Type-Options: nosniff",
  ]
