[build]
  command = "npm run prod"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "14"

[headers]
  "/*" = [
    "Cache-Control: public, max-age=0, must-revalidate",
    "X-Frame-Options: DENY",
    "X-XSS-Protection: 1; mode=block",
    "X-Content-Type-Options: nosniff",
  ]
